[theme]
primaryColor = "#000000"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F7"
textColor = "#1D1D1F"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
